(function(d,j){NodeList.prototype.forEach=HTMLCollection.prototype.forEach=Array.prototype.forEach;d.Toolkit={version:"2013.05.05"};d.exists=function(a){return void 0!==a&&null!==a};var k=function(a,b,c,g){var e=new XMLHttpRequest,d=exists(g);e.open(a,b,d);d&&(e.onload=function(){g(e)});if(c){a=new FormData;for(name in Object.keys(c))a.append(name,c[name]);c=a}e.withCredentials=!0;e.send(c);if(!d)return e.responseText};d.get=function(a,b){return k("GET",a,null,b)};d.post=function(a,b,c){return k("POST",
a,b,c)};d.create=function(a,b,c){a=j.createElement(a);if("object"==typeof b)for(property in b)Object.hasOwnProperty(b,property)||a.setAttribute(property,b[property]);"string"===typeof b&&(c=b);c&&(a.innerHTML=c);return a};var l=function(a,b){var c=a.querySelectorAll(b),g=[];if(0==c.length)return[];if(1==c.length)return c[0];for(var e=0,d=c.length;e<d;e++)g[e]=c[e];return g};d.find=function(a){return l(j,a)};d.head=document.head;d.body=document.body;var m=function(a){this.owner=a;this.events=[];this.listeners=
{}};m.prototype={record:function(a,b){this.events.pushUnique(a);exists(this.listeners[a])||(this.listeners[a]=[]);this.listeners[a].push(b)},ignore:function(a,b){var c=this.listeners[a].indexOf(b);this.listeners[a].splice(c,1)}};ClassList=function(a){this.owner=a;a=a.getAttribute("class");this.classes=!a?[]:a.split(/\s+/);this.length=0};ClassList.prototype={classes:[],__update:function(){0===this.classes.length?this.owner.removeAttribute("class"):this.owner.setAttribute("class",this.classes.join(" "));
this.length=this.classes.length},add:function(a){-1===this.classes.indexOf(a)&&this.classes.push(a);this.__update();return this.owner},remove:function(a){a=this.classes.indexOf(a);-1<a&&(this.classes.splice(a,1),this.__update());return this.owner},contains:function(a){return-1!==this.classes.indexOf(a)},item:function(a){return this.classes[a]}};var h=Array.prototype;h.pushUnique=function(a){-1===this.indexOf(a)&&this.push(a)};h.test=function(a,b){!0!==b&&(b=!1);var c,g=this.length;for(c=0;c<g;c++){t=
a(this[c]);if(b&&!t)break;if(t&&!b)return!0}return!1};h["\u5143\u306eforEach"]=h.forEach;h.forEach=function(a){this["\u5143\u306eforEach"](a);return this};h.classes=function(){if(!this["\u5185\u306eclasses"]){this["\u5185\u306eclasses"]={};var a=this;["add","remove"].forEach(function(b){a["\u5185\u306eclasses"][b]=function(){var c=arguments,g;a.forEach(function(a){g=a.classes();g[b].apply(g,c)});return a}});this["\u5185\u306eclasses"].contains=function(){var b=arguments,c;return a.test(function(a){c=
a.classes();return c.contains.apply(c,b)})}}return this["\u5185\u306eclasses"]};["add","replace"].forEach(function(a){h[a]=function(){var b=this[0];return b[a].apply(b,arguments)}});"show toggle set remove clear listen ignore listenOnce".split(" ").forEach(function(a){h[a]=function(){var b=arguments;this.map(function(c){c[a].apply(c,b)});return this}});["find","parent"].forEach(function(a){h[a]=function(){var b=[];this.forEach(function(c){c[a].apply(c,arguments).forEach(function(a){b.pushUnique(a)})});
return b}});["position","html","css","get"].forEach(function(a){h[a]=function(){var b=[];input=arguments;this.forEach(function(c){b.push(c[a].apply(c,input))});return b}});var f=HTMLElement.prototype;f.length=1;f.forEach=function(a){a(this);return this};f.css=function(a,b){if("string"===typeof b)return this.style[a]=b,""===this.get("style")&&this.set("style",""),this;if(!b&&"object"===typeof a){for(p in a)Object.hasOwnProperty(a,p)||this.css(p,a[p]);return this}return getComputedStyle(this).getPropertyValue(a)||
this.style[a]};f.position=function(){return this.getBoundingClientRect()};f.classes=function(){this["\u5185\u306eclasses"]||(this["\u5185\u306eclasses"]=new ClassList(this));return this["\u5185\u306eclasses"]};f.show=function(a){a?this.removeAttribute("data-tiny-toolkit-hidden"):this.setAttribute("data-tiny-toolkit-hidden","");return this};f.toggle=function(){this.show(d.exists(this.get("data-tiny-toolkit-hidden")));return this};f.html=function(a){return d.exists(a)?(this.innerHTML=a,this):this.innerHTML};
f.parent=function(a){return a?(a.add(this),this):this.parentNode};f.add=function(a){if("string"===typeof a)this.innerHTML+=a;else for(var b=0,c=arguments.length;b<c;b++)if(d.exists(arguments[b]))if(arguments[b]instanceof Array){var g=this;arguments[b].forEach(function(a){g.add(a)})}else this.appendChild(arguments[b]);return this};f.replace=function(a,b){if("string"===typeof a)return this.innerHTML=this.innerHTML.replace(RegExp(a,"g"),b),this;if(d.exists(a.parentNode)&&d.exists(b))return a.parentNode.replaceChild(b,
a),b;this.parentNode.replaceChild(a,this);return a};f.remove=function(a){if("string"===typeof arg)return this.replace(a,"");d.exists(a)?parseInt(a)==a?this.removeChild(this.children[a]):a.parentNode&&a.parentNode===this&&this.removeChild(a):this.parentNode.removeChild(this);return this};f.clear=function(){this.innerHTML="";return this};f.get=function(a){return a==parseInt(a)?this.children[a]:this.getAttribute(a)};f.set=function(a,b){if(d.exists(b))!1===b?this.removeAttribute(a):this.setAttribute(a,
b);else for(prop in a)Object.hasOwnProperty(a,prop)||this.setAttribute(prop,a[prop]);return this};[d.HTMLDocument?HTMLDocument.prototype:Document.prototype,HTMLElement.prototype].forEach(function(a){a.find=function(a){return l(this,a)};a.eventListeners=!1;a.__addAnEventListener=function(a,c,d){this.addEventListener(a,c,d);this.eventListeners||(this.eventListeners=new m(this));this.eventListeners.record(a,c)};a.__removeAnEventListener=function(a,c,d){this.removeEventListener(a,c,d);this.eventListeners.ignore(a,
c)};a.listen=function(a,c){this.__addAnEventListener(a,c,!1);return this};a.ignore=function(a,c){if(exists(c))this.__removeAnEventListener(a,c,!1);else{var d=this.eventListeners.listeners[a],e;if(exists(d))for(e=d.length-1;0<=e;e--)this.ignore(a,d[e])}return this};a.listenOnce=function(a,c){var d=this,e=function(){d.__removeAnEventListener(a,e,!1);c.call()};this.__addAnEventListener(a,e,!1);return this}});f=d.create("style",{type:"text/css"},"*[data-tiny-toolkit-hidden]{display:none!important;visibility:hidden!important;opacity:0!important}");
j.head.add(f);delete HTMLParagraphElement.prototype.clear})(window,document);
